### ISSUE TITLE
スマホのマイページのサイドメニューのメアドが見切れる

### ISSUE THREAD

**Issue by Yuki-Tani** [Risa-m/Ristock#20]
![Screenshot_20200609-082827](https://user-images.githubusercontent.com/22742229/84103632-9c9e1c00-aa4e-11ea-8415-be77cad00498.png)

**Comment by Risa-m** [comment]
see at https://github.com/Risa-m/Ristock/commit/849f8dbc0f9c524ade89be1f911600a4b24ac2b2
