### ISSUE TITLE
画面サイズによってHOME画面の表示が崩れる

### ISSUE THREAD

**Issue by Risa-m** [Risa-m/Ristock#21]
画面が小さい場合(iPhone6/7/8)：
説明文が見切れている
![image](https://user-images.githubusercontent.com/24539471/84105209-9611a380-aa52-11ea-80f4-7fd9150d5989.png)

画面が大きい場合(iPad Pro)：
footerの位置がずれる
![image](https://user-images.githubusercontent.com/24539471/84105230-a45fbf80-aa52-11ea-849d-d3fbcef72f39.png)

**Comment by Yuki-Tani** [comment]
![Screenshot_20200611-235037](https://user-images.githubusercontent.com/22742229/84401794-a4bcae00-ac3e-11ea-8be2-0db50f721256.png)

**Comment by Risa-m** [comment]
Thanks for your report!
This was resolved in https://github.com/Risa-m/Ristock/commit/41df0a46472924f44582df71542b081f52de19aa
This is involved in v0.1.2
