### ISSUE TITLE
2行以上のタイトルになると文字が重なる

### ISSUE THREAD

**Issue by Yuki-Tani** [Risa-m/Ristock#23]
version: 0.0.2
device: phone, PC

![Screenshot_20200610-142523](https://user-images.githubusercontent.com/22742229/84230215-7055ce80-ab26-11ea-9130-b3764465a3c0.png)

**Comment by Risa-m** [comment]
see at https://github.com/Risa-m/Ristock/commit/4ea66dabf21af3d47bfa62c85111e37cfcdb6f76
