### ISSUE TITLE
サイドメニューが左フリックで閉じない

### ISSUE THREAD

**Issue by Yuki-Tani** [Risa-m/Ristock#24]
グレーアウトしている元画面をclickすればサイドメニューは閉じるが、右から左にフリックすると閉じない。
閉じるはフリックをする人もいるので、元画面のonClickではなくonMouseDownのタイミングで閉じるべき。

例:Google検索結果ページ
スマホで確認した際のサイドメニュー
https://www.google.com/search?q=検索&oq=検索&aqs=chrome..69i57j35i39j69i61l3.1908j1j7&client=ms-android-kddi-jp-revc&sourceid=chrome-mobile&ie=UTF-8

**Comment by Risa-m** [comment]
Thanks for your comment!
https://github.com/Risa-m/Ristock/pull/57 で左スワイプした際にサイドメニューが閉じるように修正しました。
