### ISSUE TITLE
【Bug】新規登録時、カテゴリーを新たに追加してsaveを押してもカテゴリーが付与されない

### ISSUE THREAD

**Issue by Yuki-Tani** [Risa-m/Ristock#28]
入力が既にあれば、チェックマークを押さずにsaveしたときも登録されるようにすべき

**Comment by Risa-m** [comment]
Thank you for your comment!
This was resolved in https://github.com/Risa-m/Ristock/commit/c993dac4bff2512a6cff2e492ab62c5640317406
This change will be in v0.2.2.
