### ISSUE TITLE
【Bug】カテゴリー名変更直後、カテゴリーが絞り込まれた画面でも全ての項目が表示される

### ISSUE THREAD

**Issue by Yuki-Tani** [Risa-m/Ristock#33]
repro
1.カテゴリーAを用意し、いくつかの項目に付与
2.メイン画面でカテゴリーAを選択、項目を絞り込む
3.カテゴリー編集画面を表示、カテゴリーAをカテゴリーBに改名
4.メイン画面に戻ると、カテゴリーBが選択済みになっているが、表示では絞り込みは行われていない

**Comment by Risa-m** [comment]
Thank you for your comment!
This was resolved in https://github.com/Risa-m/Ristock/commit/febbf8fdf3020294be477c02ef7a6ce0d71abf70
This change will be in v0.2.2.
